"""revisi1

Revision ID: 0f5f941980e4
Revises: aea3d30bab4e
Create Date: 2024-05-15 12:24:48.949165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f5f941980e4'
down_revision = 'aea3d30bab4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jawaban_responden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bukti_pelaksanaan', sa.String(length=50), nullable=True))

    with op.batch_alter_table('responden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nip', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('jabatan', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('asal_instansi', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('no_hp', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=False))
        batch_op.drop_column('alamat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alamat', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('no_hp')
        batch_op.drop_column('asal_instansi')
        batch_op.drop_column('jabatan')
        batch_op.drop_column('nip')

    with op.batch_alter_table('jawaban_responden', schema=None) as batch_op:
        batch_op.drop_column('bukti_pelaksanaan')

    # ### end Alembic commands ###
