"""satu

Revision ID: 3a5a05acb163
Revises: 
Create Date: 2024-05-11 03:09:58.472761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5a05acb163'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('alamat', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kuis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teks', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kuis_responden',
    sa.Column('kuis_id', sa.Integer(), nullable=False),
    sa.Column('responden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kuis_id'], ['kuis.id'], ),
    sa.ForeignKeyConstraint(['responden_id'], ['responden.id'], ),
    sa.PrimaryKeyConstraint('kuis_id', 'responden_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kuis_responden')
    op.drop_table('kuis')
    op.drop_table('responden')
    op.drop_table('kategori')
    # ### end Alembic commands ###
