"""tambahkan jawaban

Revision ID: a99f169be071
Revises: 3a5a05acb163
Create Date: 2024-05-11 18:14:45.774871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99f169be071'
down_revision = '3a5a05acb163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jawaban', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responden', schema=None) as batch_op:
        batch_op.drop_column('jawaban')

    # ### end Alembic commands ###
